
package com.holidaywebservice.holidayservice_v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolidayService2Soap", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolidayService2Soap {


    /**
     * Get the available countries.
     * 
     * @return
     *     returns com.holidaywebservice.holidayservice_v2.ArrayOfCountryCode
     */
    @WebMethod(operationName = "GetCountriesAvailable", action = "http://www.holidaywebservice.com/HolidayService_v2/GetCountriesAvailable")
    @WebResult(name = "GetCountriesAvailableResult", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
    @RequestWrapper(localName = "GetCountriesAvailable", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetCountriesAvailable")
    @ResponseWrapper(localName = "GetCountriesAvailableResponse", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetCountriesAvailableResponse")
    public ArrayOfCountryCode getCountriesAvailable();

    /**
     * Get the available holidays for a specified country.
     * 
     * @param countryCode
     * @return
     *     returns com.holidaywebservice.holidayservice_v2.ArrayOfHolidayCode
     */
    @WebMethod(operationName = "GetHolidaysAvailable", action = "http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysAvailable")
    @WebResult(name = "GetHolidaysAvailableResult", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
    @RequestWrapper(localName = "GetHolidaysAvailable", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysAvailable")
    @ResponseWrapper(localName = "GetHolidaysAvailableResponse", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysAvailableResponse")
    public ArrayOfHolidayCode getHolidaysAvailable(
        @WebParam(name = "countryCode", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        Country countryCode);

    /**
     * Get the date of a specific holiday.
     * 
     * @param year
     * @param countryCode
     * @param holidayCode
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetHolidayDate", action = "http://www.holidaywebservice.com/HolidayService_v2/GetHolidayDate")
    @WebResult(name = "GetHolidayDateResult", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
    @RequestWrapper(localName = "GetHolidayDate", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidayDate")
    @ResponseWrapper(localName = "GetHolidayDateResponse", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidayDateResponse")
    public XMLGregorianCalendar getHolidayDate(
        @WebParam(name = "countryCode", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        Country countryCode,
        @WebParam(name = "holidayCode", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        String holidayCode,
        @WebParam(name = "year", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        int year);

    /**
     * Get the holidays for a date range.
     * 
     * @param endDate
     * @param countryCode
     * @param startDate
     * @return
     *     returns com.holidaywebservice.holidayservice_v2.ArrayOfHoliday
     */
    @WebMethod(operationName = "GetHolidaysForDateRange", action = "http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysForDateRange")
    @WebResult(name = "GetHolidaysForDateRangeResult", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
    @RequestWrapper(localName = "GetHolidaysForDateRange", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysForDateRange")
    @ResponseWrapper(localName = "GetHolidaysForDateRangeResponse", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysForDateRangeResponse")
    public ArrayOfHoliday getHolidaysForDateRange(
        @WebParam(name = "countryCode", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        Country countryCode,
        @WebParam(name = "startDate", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        XMLGregorianCalendar endDate);

    /**
     * Get the holidays for an entire year.
     * 
     * @param year
     * @param countryCode
     * @return
     *     returns com.holidaywebservice.holidayservice_v2.ArrayOfHoliday
     */
    @WebMethod(operationName = "GetHolidaysForYear", action = "http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysForYear")
    @WebResult(name = "GetHolidaysForYearResult", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
    @RequestWrapper(localName = "GetHolidaysForYear", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysForYear")
    @ResponseWrapper(localName = "GetHolidaysForYearResponse", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysForYearResponse")
    public ArrayOfHoliday getHolidaysForYear(
        @WebParam(name = "countryCode", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        Country countryCode,
        @WebParam(name = "year", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        int year);

    /**
     * Get the holidays for a specific month.
     * 
     * @param month
     * @param year
     * @param countryCode
     * @return
     *     returns com.holidaywebservice.holidayservice_v2.ArrayOfHoliday
     */
    @WebMethod(operationName = "GetHolidaysForMonth", action = "http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysForMonth")
    @WebResult(name = "GetHolidaysForMonthResult", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
    @RequestWrapper(localName = "GetHolidaysForMonth", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysForMonth")
    @ResponseWrapper(localName = "GetHolidaysForMonthResponse", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", className = "com.holidaywebservice.holidayservice_v2.GetHolidaysForMonthResponse")
    public ArrayOfHoliday getHolidaysForMonth(
        @WebParam(name = "countryCode", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        Country countryCode,
        @WebParam(name = "year", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        int year,
        @WebParam(name = "month", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/")
        int month);

}
